### ISSUE TITLE
Installation script can't work for non-root user with sudo

### ISSUE THREAD

**Issue by resursator** [amnezia-vpn/amnezia-client#363]
**Describe the bug**
Client tries to install several programs on the server with these lines:
```
if [ "$dist" = "debian" ]; then export DEBIAN_FRONTEND=noninteractive; fi;\
if ! command -v sudo > /dev/null 2>&1; then $pm update -yq; $pm install -yq sudo; fi;\
if ! command -v fuser > /dev/null 2>&1; then $pm install -yq psmisc; fi;\
if ! command -v lsof > /dev/null 2>&1; then $pm install -yq lsof; fi;\
if ! command -v docker > /dev/null 2>&1; then $pm update -yq; $pm install -yq $docker_pkg;\
  if [ "$dist" = "fedora" ] || [ "$dist" = "debian" ]; then sudo systemctl enable docker && sudo systemctl start docker; fi;\
fi;\
```
However, it can't work for non-root users, even if the user can use sudo without password. It can be fixed, if "$pm install" lines used sudo, so the script could work for users with properly setuped sudo.

**To Reproduce**
1. Install any protocol on the server, that haven't psmisc, lsof or $docker_pkg already installed
2. See error "Internal error"

**Expected behavior**
Selected protocol being installed on the server

**Log files**
[AmneziaVPN.log](https://github.com/amnezia-vpn/amnezia-client/files/12851029/AmneziaVPN.log)

**Screenshots**
![image](https://github.com/amnezia-vpn/amnezia-client/assets/8604513/db6e7436-8aa8-4dbb-9b71-ab93c56b7ec8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 3.1.0.1

**Server (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by Evgsiv** [comment]
On OS Ubuntu 22.04 I fixed added "auth sufficiencent pam_permit.so" line to /etc/pam.d/sudo

**Comment by SagiSasha** [comment]
Good afternoon.
I encountered a similar problem.

I created the user “amnezia”, added “usermod -aG sudo amnezia” to the group, then added “ALL=(ALL) NOPASSWD: ALL” to the “/etc/sudoers” file.
![Снимок экрана от 2023-11-26 19-46-41](https://github.com/amnezia-vpn/amnezia-client/assets/152085433/abb6f2ee-41c2-4f21-9769-3f1dea8e8662)

But when starting the installation it still gives an error:
"sftp error: Permission denied"
![Снимок экрана от 2023-11-26 19-44-32](https://github.com/amnezia-vpn/amnezia-client/assets/152085433/a11970b0-d651-4332-8a90-ca10db681748)

Log:
Nov 26 16:40:52 server sshd[3232]: Accepted password for amnezia from 123.45.67.89 port 34676 ssh2
Nov 26 16:40:52 server sshd[3232]: pam_unix(sshd:session): session opened for user amnezia(uid=1000) by (uid=0)
Nov 26 16:40:52 server systemd-logind[384]: New session 100 of user amnezia.
Nov 26 16:40:52 server systemd[1]: Started Session 100 of User amnezia.
Nov 26 16:40:53 server sudo[3243]: **pam_unix(sudo:auth): conversation failed**
Nov 26 16:40:53 server sudo[3243]: **pam_unix(sudo:auth): auth could not identify password for [amnezia]**
Nov 26 16:40:53 server sudo[3248]: **pam_unix(sudo:auth): conversation failed**
Nov 26 16:40:53 server sudo[3248]: **pam_unix(sudo:auth): auth could not identify password for [amnezia]**

Please tell me what I did wrong?
Thank you.

**Comment by SagiSasha** [comment]
Added "auth sufficient pam_permit.so" to the /etc/pam.d/sudo file.
But this did not help, the installation error was "sftp error: Permission denied".
![Снимок экрана от 2023-11-27 10-34-53](https://github.com/amnezia-vpn/amnezia-client/assets/152085433/10226219-a2d9-4f2d-8b3f-9601c2ab0974)

**Comment by pokamest** [comment]
[SagiSasha](https://github.com/SagiSasha) What is app version? Does sudo ps requires password?

**Comment by SagiSasha** [comment]
@pokamest , I have Ubuntu OS 22, client version of the program AmneziaVPN_Linux_4.0.8.6.
On the server I tried to open /root as the user “amnezia”, it did not require a password.

**Comment by niki4xxxxx** [comment]
@pokamest, Hello, I have the same issue with installation protocols.

====Server====

- Kernel: 5.4.0-169-generic x86_64 
- bits: 64 
- compiler: gcc v: 9.4.0
- Distro: Ubuntu 20.04.6 LTS (Focal Fossa) 
- Machine Type: Kvm
- AmneziaVPN_Linux_4.1.0.1 (client on my home PC)



====Errors====

- "sftp error: Permission denied"


====Tried====
Added "auth sufficient pam_permit.so" to the /etc/pam.d/sudo file. But this did not help, the installation error was "sftp error: Permission denied"

====Logs====
```
Jan 18 20:06:02 weaselcloud-5469 systemd-logind[693]: New session 20 of user nick.
Jan 18 20:06:03 weaselcloud-5469 kernel: [UFW BLOCK] IN=ens3 OUT= MAC=fa:16:3e:33:c0:22:7c:25:86:93:7d:60:08:00 SRC=5.53.113.90 DST=45.144.235.250 LEN=52 TOS=0x00 PREC=0x00 TTL=112 ID=27611 DF PROTO=TCP SPT=8176 DPT=64452 WINDOW=64240 RES=0x00 SYN URGP=0 
Jan 18 20:06:03 weaselcloud-5469 sudo[5174]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:03 weaselcloud-5469 sudo[5174]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:04 weaselcloud-5469 sudo[5180]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:04 weaselcloud-5469 sudo[5180]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:07 weaselcloud-5469 sudo[5191]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:07 weaselcloud-5469 sudo[5191]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:07 weaselcloud-5469 sudo[5199]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:07 weaselcloud-5469 sudo[5199]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:07 weaselcloud-5469 sudo[5204]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:07 weaselcloud-5469 sudo[5204]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:07 weaselcloud-5469 sudo[5209]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:07 weaselcloud-5469 sudo[5209]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:08 weaselcloud-5469 sudo[5210]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:08 weaselcloud-5469 sudo[5210]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:08 weaselcloud-5469 sudo[5211]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:08 weaselcloud-5469 sudo[5211]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:08 weaselcloud-5469 sudo[5213]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:08 weaselcloud-5469 sudo[5213]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:08 weaselcloud-5469 sudo[5214]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:08 weaselcloud-5469 sudo[5214]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:08 weaselcloud-5469 sudo[5215]: pam_unix(sudo:auth): conversation failed
Jan 18 20:06:08 weaselcloud-5469 sudo[5215]: pam_unix(sudo:auth): auth could not identify password for [nick]
Jan 18 20:06:08 weaselcloud-5469 sshd[5091]: pam_unix(sshd:session): session closed for user nick
Jan 18 20:06:08 weaselcloud-5469 systemd[1]: session-20.scope: Succeeded.
Jan 18 20:06:08 weaselcloud-5469 systemd-logind[693]: Session 20 logged out. Waiting for processes to exit.
Jan 18 20:06:08 weaselcloud-5469 systemd-logind[693]: Removed session 20.
Jan 18 20:06:09 weaselcloud-5469 sudo[5228]:     nick : TTY=pts/0 ; PWD=/home/nick ; USER=root ; COMMAND=/usr/bin/journalctl -b 0
Jan 18 20:06:09 weaselcloud-5469 sudo[5228]: pam_unix(sudo:session): session opened for user root by nick(uid=0)


```

**Comment by niko-zvt** [comment]
@pokamest +1 (iOS App 4.2.1.0 Jan 25 2024 + Ubuntu 22)

UPD: Using the `root` user avoided the problem.

**Comment by pokamest** [comment]
Amnezia expects that the commands launched with sudo won't require password.
Amnezia won't make any changes in sudoers file.
In case if you providing non-root user to Amnezia, you should be sure this user have enough permissions to run sudo without password, and SFTP is enabled for ssh.

@niki4xxxxx, you need to check if SFTP is enabled for ssh.

Basically issue fixed in https://github.com/amnezia-vpn/amnezia-client/commit/d92729d346e14a7ee8ad3ba646202605d9642789, so I'm closing this issue.
If something wrong in latest release, please open new issue and fully describe your case, including log files.

**Comment by GingerFish** [comment]
Sorry, but issue is NOT resolved. I have a latest Amnezia release, Win10, VDS on Debian 11. Sudo rights without password granted and works, user is in sudo group. lsof, docker and other installed. But I'm still getting this error and this is annooying. Under root I have no problems, but I don't wan't to use or share root for such things.

**Comment by drizzle-mizzle** [comment]
Yeah, it is not fixed at all
