### ISSUE TITLE
ERR_SOCKET_NOT_CONNECTED in Chrome

### ISSUE THREAD

**Issue by cryptonoise** [amnezia-vpn/amnezia-client#945]
**Describe the bug**
**ERR_SOCKET_NOT_CONNECTED** - When opening a new site (new tab) that has not been opened before, this error occurs for a couple of seconds in the chrome browser when using AmnesiaVPN. 
When using other VPN clients with the same connection configurations, there is no such error. 
In Firefox - all ok. 
Issue has been observed by several people for a long time. Search the [telegram chat](https://t.me/amnezia_vpn) for **ERR_SOCKET_NOT_CONNECTED**

**To Reproduce**
1. Connect using AmnesiaVPN
2. Open Google Chrome browser
3. Open any new website that has not been opened before

**Desktop:**
 - OS: [MacOS Sonoma 14.5]

**Comment by VladTolm** [comment]
Any updates on this issue?

This error is incredibly frustrating

**Comment by vintikzzz** [comment]
Disabling quic protocol solved this problem...
Here is a [guide](https://support.eset.com/en/kb6757-disable-quic-protocol-in-google-chrome-browser#:~:text=In%20the%20URL%20address%20field,%3A%2F%2Fflags%20and%20press%20Enter.&text=Type%20quic%20into%20the%20Search,next%20to%20Experimental%20QUIC%20protocol.) how to do that.

**Comment by LeWombat** [comment]
Check this bag pls

**Comment by t3chn0pr13st** [comment]
Looks like this advice may help https://www.reddit.com/r/AmneziaVPN/comments/1gy8vrn/comment/m1h9o9g/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by vintikzzz** [comment]
@t3chn0pr13st does it work for you?
No for me...

**Comment by ragozin-nikita** [comment]
Resolved it by:
WiFi settings -> TCP/IP Tab -> ipv6 Configuration -> Link-Local Only

**Comment by vintikzzz** [comment]
@ragozin-nikita it's strange, your soultion doesn't work me...
But when I switch to auto the issue dissapeared... Keep watching...

**Comment by vlad-artyomov** [comment]
Nothing helps in my case, tried:

- Enable/disable IPv6 on the system level or in Wi-Fi settings
- Change settings DNS in Chrome

In Safari no problems, the issue with SOCKET_NOT_CONNECTED happens only in Chrome when the AmneziaWG connection is active. 

The issue is **quite critical** because apps like Jira do not work, and I have to refresh the page 5 times to get all the data loaded.

**Comment by GGGSPB** [comment]
I am inclined to consider AmneziaVPN broken because I am facing this issue every couple of minutes now. I didn't have it a single time for the first 3 months of use, nothing changed since but now I have it constantly. 

Tried:

- Reinstalled AmneziaVPN on my VPS
- Regenerated configs
- Turned Amnezia DNS on & off
- Turned IPv6 off

Issue still persists.

**Comment by vlad-artyomov** [comment]
I found a solution — in my case, the problem was caused by the KillSwitch feature on the client app. Once I disabled it, everything worked perfectly.

https://docs.amnezia.org/documentation/instructions/killswitch/

**Comment by kfastov** [comment]
The bug still persists. Disabling killswitch is not a viable option, because it's a vital feature.

**Comment by Insanefoam** [comment]
Bump, same issue

**Comment by youlovejohnny** [comment]
Bump, still happens

**Comment by intexcor** [comment]
macOS pf (firewall) in Amnesia has a chain of anchors with rules. Two of them were in conflict:                                                                                     
   
  - 200.allowVPN — pass out on utun* (skip VPN traffic)                                                                                                                    
  - 250.blockIPv6 — block return out inet6 (block all IPv6)

  In pf, the rules work according to the last match wins principle — the last matched rule wins. Therefore, rule 250 overwritten rule 200 for IPv6 packets going through a VPN.
  the tunnel. IPv6 traffic inside utun was blocked by its own firewall.

  Because of this, Chrome (Happy Eyeballs / QUIC) tried IPv6 → lock → timeout → slow reverse on IPv4 → ERR_SOCKET_NOT_CONNECTED.

**Comment by DanyaONELOVE** [comment]
Had this issue on Mac, I've tried EVERYTHING, and nothing has helped, except for these two commands:
sudo networksetup -setv6off Wi-Fi
sudo pfctl -F all

**Comment by mikkan-39** [comment]
Bump, still happening. Disabling the kill switch and ipv6 kind of solves the ERR_SOCKET_NOT_CONNECTED issue, but breaks a lot of websites and is a no-go for those who need ipv6 for whatever reason.

**Comment by Jokero** [comment]
@intexcor hi, what's the status of your PR?
